# Generated by Django 5.1.7 on 2025-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название задачи (до 100 символов)', max_length=100)),
                ('is_completed', models.BooleanField(default=False, help_text='Статус выполнения задачи')),
            ],
        ),
    ]
